server:
  port: 8081
spring:
  application:
    name: secure-auth-service

  datasource:
    url: jdbc:h2:mem:secureauth
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"